### ISSUE TITLE
Sometimes color hints reveals two colors at once by mistake

### ISSUE THREAD

**Issue by BlueInt32** [bstnfrmry/hanabi#217]
I think there is a bug sometimes when one player gives a color-hint (classic 2 players mode).

For example in https://hanabi.cards/fr/SexualLoonBrown, at step 28/63, when Blablou gives hint of blue cards, both the top left Blablette's blue 2 and the top right white get color-revealed. I guess there is some mechanism that will try to reveal "sure" cards if there are any, but in this case it is clearly wrong that any white card should be revealed by hinting the blue ones.

**Comment by bstnfrmry** [comment]
Hey @BlueInt32, thanks for the report and for providing a link :)

So I'm not 100% sure there's an issue here. From what I understand

This is Blablette's game at turn 27.

![image](https://user-images.githubusercontent.com/1478542/103181588-ee02e100-48a2-11eb-9fcd-6bad1df78c33.png)

From previously received hints, the right-most card is either blue or white.

Since hints apply to all cards in hand. So at turn 28, the hint 

![image](https://user-images.githubusercontent.com/1478542/103181620-6073c100-48a3-11eb-90e5-848d379b2117.png)

also means : "your cards B C D E are *not* blue"

So by elimination, E, the right-most card can only be white.

---

That's my interpretation of the situation but I might have missed something. If so please let me know 😉

**Comment by BlueInt32** [comment]
@bstnfrmry Oh I see. In fact I didn't know the engine could go as far as to deduce these kinds of things automatically. So this is not a bug, but a feature, right ? 😄 
Thanks for the thorough answer.

**Comment by bstnfrmry** [comment]
Yep exactly, it's a feature 😉

This can lead to cool strategies where negative hints can also have a lot of value!
